# Generated by Django 6.1.1 on 2026-09-21 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Littoral - Centre VIP', max_length=100)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='agencies.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('amenities', models.TextField(blank=True, help_text='Climatisation, Wi-Fi, etc.')),
                ('registration', models.CharField(blank=True, max_length=20)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='agencies.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('available_capacity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Programmé'), ('boarding', 'Embarquement'), ('departed', 'Parti'), ('cancelled', 'Annulé')], default='scheduled', max_length=20)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='agencies.agency')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='travel.line')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='LineStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField(help_text="Ordre de l'arrêt (1 pour le départ, 2 pour le premier arrêt, etc.)")),
                ('duration_from_start', models.DurationField(default='00:00:00', help_text='Durée depuis le départ (00:00:00 pour le point de départ)')),
                ('price_from_start', models.DecimalField(decimal_places=2, default=0, help_text='Prix cumulé depuis le départ (0 pour le point de départ)', max_digits=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.city')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='travel.line')),
            ],
            options={
                'ordering': ['stop_order'],
                'unique_together': {('line', 'stop_order')},
            },
        ),
    ]
