# Generated by Django 6.1.1 on 2026-10-01 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agency_booking_cutoff_minutes_and_more'),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('phone', models.CharField(max_length=30, verbose_name='Téléphone mobile')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='N° Permis de conduire (Catégorie D)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif / En service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Chauffeur',
                'verbose_name_plural': 'Chauffeurs',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='departure',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departures', to='travel.driver', verbose_name='Chauffeur assigné'),
        ),
    ]
