# Generated by Django 6.1.1 on 2026-10-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_driver_departure_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('in_trip', 'En voyage'), ('maintenance', 'En maintenance'), ('out_of_service', 'Hors service')], default='available', max_length=20, verbose_name='Disponibilité opérationnelle'),
        ),
        migrations.AlterField(
            model_name='departure',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programmé'), ('boarding', 'Embarquement'), ('departed', 'Parti / Clôturé'), ('cancelled', 'Annulé')], default='scheduled', max_length=20),
        ),
    ]
