# Generated by Django 6.1.1 on 2026-10-01 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_vehicle_status_alter_departure_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linestop',
            name='duration_from_start',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Durée depuis le départ (00:00:00 pour le point de départ)'),
        ),
    ]
