# Generated by Django 6.1.1 on 2026-10-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10, verbose_name='Prix du trajet complet (FCFA)'),
        ),
    ]
