# Generated by Django 6.1.1 on 2026-10-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_id_number_user_id_type_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Titre de l'alerte")),
                ('message', models.TextField(verbose_name='Détails du problème')),
                ('level', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('error', 'Erreur Critique')], default='error', max_length=20, verbose_name='Niveau de gravité')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Résolu ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerte Système',
                'verbose_name_plural': 'Alertes Système',
                'ordering': ['-created_at'],
            },
        ),
    ]
