# Generated by Django 6.1.1 on 2026-10-04 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_systemalert'),
        ('agencies', '0004_agency_platform_fee_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency',
            field=models.ForeignKey(blank=True, help_text="L'agence à laquelle cet employé est rattaché (pour managers/agents).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='agencies.agency'),
        ),
    ]
