# Generated by Django 6.1.1 on 2026-10-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Solde Portefeuille'),
        ),
    ]
