# Generated by Django 6.1.1 on 2026-10-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_type',
            field=models.CharField(blank=True, choices=[('CNI', "Carte Nationale d'Identité (CNI)"), ('PASSPORT', 'Passeport'), ('RECEIPT', 'Récépissé de CNI'), ('STUDENT', "Carte d'étudiant / d'élève"), ('OTHER', 'Autre (Aucune pièce officielle)')], default='CNI', max_length=20),
        ),
    ]
