# Generated by Django 6.1.1 on 2026-09-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='booking_cutoff_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Clôture des ventes en ligne (minutes avant départ)'),
        ),
        migrations.AddField(
            model_name='agency',
            name='cancellation_deadline_hours',
            field=models.PositiveIntegerField(default=2, help_text="Délai maximum d'annulation (heures avant départ)"),
        ),
        migrations.AddField(
            model_name='agency',
            name='currency',
            field=models.CharField(default='FCFA', max_length=10),
        ),
        migrations.AddField(
            model_name='agency',
            name='date_format',
            field=models.CharField(choices=[('d/m/Y', 'JJ/MM/AAAA'), ('Y-m-d', 'AAAA-MM-JJ')], default='d/m/Y', max_length=20),
        ),
        migrations.AddField(
            model_name='agency',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('de', 'Deutsch')], default='fr', max_length=10),
        ),
        migrations.AddField(
            model_name='agency',
            name='legal_name',
            field=models.CharField(blank=True, default='', help_text='Raison sociale officielle', max_length=150),
        ),
        migrations.AddField(
            model_name='agency',
            name='license_number',
            field=models.CharField(blank=True, default='N° MINT-TRANS-CMR/2024-AGY', help_text='Agrément ministériel de transport', max_length=100),
        ),
        migrations.AddField(
            model_name='agency',
            name='notify_agent_sound',
            field=models.BooleanField(default=True, help_text="Alerte sonore au guichet lors d'une nouvelle réservation"),
        ),
        migrations.AddField(
            model_name='agency',
            name='notify_email_ticket',
            field=models.BooleanField(default=True, help_text='Envoi du billet électronique par email'),
        ),
        migrations.AddField(
            model_name='agency',
            name='notify_sms_booking',
            field=models.BooleanField(default=True, help_text='SMS immédiat de confirmation au voyageur'),
        ),
        migrations.AddField(
            model_name='agency',
            name='notify_sms_reminder',
            field=models.BooleanField(default=True, help_text='SMS de rappel 2h avant le départ'),
        ),
        migrations.AddField(
            model_name='agency',
            name='primary_color',
            field=models.CharField(default='#2563eb', help_text='Code couleur HEX (ex: #2563eb)', max_length=20),
        ),
        migrations.AddField(
            model_name='agency',
            name='printer_format',
            field=models.CharField(choices=[('a4', 'Standard A4 (Factures & Billets complets)'), ('thermal_80', 'Thermique 80mm (Guichet POS Standard)'), ('thermal_58', 'Thermique 58mm (Guichet POS Compact)')], default='a4', max_length=20),
        ),
        migrations.AddField(
            model_name='agency',
            name='scale_enabled',
            field=models.BooleanField(default=False, help_text="Connexion d'une balance connectée pour la pesée des bagages"),
        ),
        migrations.AddField(
            model_name='agency',
            name='scanner_enabled',
            field=models.BooleanField(default=True, help_text='Activer la détection automatique du lecteur de QR code / douchette'),
        ),
        migrations.AddField(
            model_name='agency',
            name='tax_id',
            field=models.CharField(blank=True, default='', help_text="Numéro d'Identifiant Fiscal Unique / RCCM", max_length=50),
        ),
        migrations.AddField(
            model_name='agency',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Mode Clair'), ('dark', 'Mode Sombre'), ('system', 'Synchronisé avec le système')], default='light', max_length=20),
        ),
        migrations.AddField(
            model_name='agency',
            name='ticket_terms',
            field=models.TextField(blank=True, default="1. Présentation obligatoire de la CNI/Passeport physique à l'embarquement.\n2. Présence requise au quai 30 minutes avant l'heure de départ.\n3. Franchise bagage : 30 kg par passager. Tout excédent est soumis à taxation.\n4. Billet modifiable jusqu'à 2h avant le départ, non remboursable après départ.", help_text='Conditions générales et mentions légales imprimées au bas du ticket'),
        ),
        migrations.AddField(
            model_name='agency',
            name='time_format',
            field=models.CharField(choices=[('24h', '24 Heures (14:30)'), ('12h', '12 Heures AM/PM (02:30 PM)')], default='24h', max_length=10),
        ),
        migrations.AddField(
            model_name='agency',
            name='timezone',
            field=models.CharField(default='Africa/Douala', max_length=50),
        ),
        migrations.AddField(
            model_name='agency',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Taux de TVA applicable en %', max_digits=5),
        ),
    ]
