# Generated by Django 6.1.1 on 2026-10-01 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agency_booking_cutoff_minutes_and_more'),
        ('bookings', '0004_booking_paid_at_booking_payment_method_and_more'),
        ('travel', '0003_vehicle_status_alter_departure_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('id_collision', 'Usurpation / Même CNI sous plusieurs identités'), ('cashier_cancellation', "Taux d'annulation anormal (Suspicion Caissier)"), ('price_mismatch', 'Tarif hors grille officielle'), ('unpaid_boarding', 'Passager embarqué sans paiement validé'), ('cash_register', 'Écart de réconciliation caisse / billets'), ('bogus_identity', 'Identité ou numéro manifestement fictif'), ('suspicious_pattern', 'Comportement suspect détecté par IA')], max_length=40)),
                ('severity', models.CharField(choices=[('critical', 'Critique'), ('high', 'Élevée'), ('medium', 'Moyenne'), ('low', 'Faible')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text="Explication de l'incohérence par Gemini")),
                ('gemini_recommendation', models.TextField(blank=True, default='', help_text="Action recommandée par l'IA")),
                ('evidence_data', models.JSONField(blank=True, default=dict, help_text='Données chiffrées / Preuves détectées')),
                ('ai_confidence', models.FloatField(default=0.92, help_text='Indice de confiance de la détection (0 à 1)')),
                ('status', models.CharField(choices=[('pending', "En attente d'arbitrage"), ('confirmed', 'Fraude / Incohérence confirmée'), ('dismissed', 'Classée sans suite (Fausse alerte)'), ('regularized', 'Régularisée')], default='pending', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='', help_text='Motif de la décision humaine')),
                ('action_taken', models.CharField(blank=True, default='', help_text='Action effectuée lors du traitement', max_length=150)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='agencies.agency')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='bookings.booking')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashier_anomalies', to=settings.AUTH_USER_MODEL)),
                ('departure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='travel.departure')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_anomalies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Anomalie d'Audit Gemini",
                'verbose_name_plural': "Anomalies d'Audit Gemini",
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='AgencyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('danger', 'Urgent / Critique')], default='warning', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='agencies.agency')),
                ('anomaly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='agencies.auditanomaly')),
            ],
            options={
                'verbose_name': 'Notification Agence',
                'verbose_name_plural': 'Notifications Agence',
                'ordering': ['-created_at'],
            },
        ),
    ]
