# Generated by Django 6.1.1 on 2026-10-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_auditanomaly_agencynotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='platform_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Frais de plateforme EasyTravel (%)', max_digits=5),
        ),
    ]
