# Generated by Django 6.1.1 on 2026-09-21 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=12, unique=True)),
                ('traveler_name', models.CharField(max_length=150)),
                ('traveler_phone', models.CharField(max_length=20)),
                ('traveler_email', models.EmailField(blank=True, max_length=254)),
                ('seats_reserved', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arrival_stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arriving_bookings', to='travel.linestop')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='travel.departure')),
                ('departure_stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departing_bookings', to='travel.linestop')),
            ],
        ),
    ]
