# Generated by Django 6.1.1 on 2026-09-26 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='id_number',
            field=models.CharField(default='', max_length=50, verbose_name="Numéro de la pièce d'identité"),
        ),
        migrations.AddField(
            model_name='booking',
            name='id_type',
            field=models.CharField(choices=[('CNI', "Carte Nationale d'Identité (CNI)"), ('PASSPORT', 'Passeport'), ('RECEIPT', 'Récépissé de CNI')], default='CNI', max_length=20, verbose_name='Type de pièce'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reference',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée')], default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='traveler_email',
            field=models.EmailField(max_length=254, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='traveler_name',
            field=models.CharField(max_length=150, verbose_name='Nom complet du voyageur'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='traveler_phone',
            field=models.CharField(max_length=25, verbose_name='Numéro de téléphone camerounais'),
        ),
    ]
