# Generated by Django 6.1.1 on 2026-09-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_id_number_booking_id_type_booking_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('boarded', 'Embarqué(e)'), ('cancelled', 'Annulée')], default='confirmed', max_length=20),
        ),
    ]
