# Generated by Django 6.1.1 on 2026-10-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'encaissement"),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces (Guichet)'), ('orange_money', 'Orange Money'), ('mtn_momo', 'MTN Mobile Money'), ('card', 'Carte Bancaire'), ('online', 'Paiement en ligne')], default='cash', max_length=30, verbose_name="Mode d'encaissement"),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Payé / Encaissé'), ('pending', 'En attente de règlement'), ('refunded', 'Remboursé'), ('failed', 'Échoué / Non réglé')], default='paid', max_length=20, verbose_name='Statut du paiement'),
        ),
    ]
