# Generated by Django 6.1.1 on 2026-10-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_paid_at_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_operator',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Opérateur (MTN, Orange, etc.)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ID Transaction Passerelle'),
        ),
    ]
