# Generated by Django 6.1.1 on 2026-10-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_payment_operator_booking_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='agency_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Montant reversé à l'agence", max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Frais de service EasyTravel', max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Montant total payé par le client (Agence + Frais)', max_digits=10),
        ),
    ]
