# Generated by Django 6.1.1 on 2026-10-04 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_agency_amount_booking_platform_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Note sur 5')),
                ('comment', models.TextField(blank=True, help_text='Commentaire du client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Sondage de satisfaction',
                'verbose_name_plural': 'Sondages de satisfaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
