# Generated by Django 6.1.1 on 2026-10-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_bookingcart_booking_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Espèces (Guichet)'), ('orange_money', 'Orange Money'), ('mtn_momo', 'MTN Mobile Money'), ('card', 'Carte Bancaire'), ('online', 'Paiement en ligne')], max_length=30, null=True, verbose_name="Mode d'encaissement"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Payé / Encaissé'), ('pending', 'En attente de règlement'), ('refunded', 'Remboursé'), ('failed', 'Échoué / Non réglé')], default='pending', max_length=20, verbose_name='Statut du paiement'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('boarded', 'Embarqué(e)'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
    ]
