# Generated by Django 6.1.1 on 2026-10-07 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_payment_method_and_more'),
        ('travel', '0005_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrival_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arriving_bookings', to='travel.linestop'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departing_bookings', to='travel.linestop'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name="Numéro de la pièce d'identité"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id_type',
            field=models.CharField(choices=[('cni', "Carte Nationale d'Identité (CNI)"), ('passport', 'Passeport'), ('school_card', 'Carte scolaire'), ('other', 'Autre'), ('none', 'Aucune pièce')], default='none', max_length=20, verbose_name='Type de pièce'),
        ),
    ]
