# Generated by Django 6.1.1 on 2026-10-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_booking_arrival_stop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='traveler_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse email'),
        ),
    ]
