# Generated by Django 6.1.1 on 2026-10-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_alter_booking_traveler_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='companions',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Accompagnants'),
        ),
    ]
